  style:
    WildcardImport:
      active: false
    MagicNumber:
      active: true
      excludes:

  naming:
    FunctionNaming:
      active: true
      ignoreAnnotated: [ 'Composable' ]


  complexity:
    LongParameterList:
      active: true
      functionThreshold: 8
      constructorThreshold: 8
      ignoreAnnotated: [ 'Composable' ]
      excludes:


  exceptions:
    TooGenericExceptionCaught:
      active: true
      excludes:

  formatting:
    NewLineAtEndOfFile:
      active: true
      autoCorrect: true
    NoWildcardImports:
      active: false
    SpacingBetweenDeclarationsWithAnnotations:
      active: true
      autoCorrect: true
    NoMultipleSpaces:
      active: true
      autoCorrect: true
    ConsecutiveBlankLines:
      active: true
      autoCorrect: true
      maxBlankLines: 1
    TrailingWhitespace:
      active: true
      autoCorrect: true
    NoEmptyClassBody:
      active: true
      autoCorrect: true
    SpacingAroundCurlyBraces:
      active: true
      autoCorrect: true
      allowBlankLines: false
    SpacingInsideParens:
      active: true
      autoCorrect: true
    ModifierOrder:
      active: true
      autoCorrect: true
    NoUnusedImports:
      active: true
      autoCorrect: true
    SpacingAroundOperators:
      active: true
      autoCorrect: true
    UnusedPrivateMember:
      active: true
      autoCorrect: true